In [1]:
import importlib

In [2]:
module = importlib.import_module("torch.nn")
print(getattr(module,"Module"))

<class 'torch.nn.modules.module.Module'>


In [3]:
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--f",help="tre")
print(parser._action_groups[0])
print(parser._action_groups[1])

In [4]:
from transformers import AutoTokenizer,AutoModelForMaskedLM,BertTokenizer,BertModel,BertForMaskedLM
import torch
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForMaskedLM.from_pretrained("bert-base-uncased")
text = "I am a student"
tokenized_text = tokenizer.tokenize(text)
masked_index = 2
tokenized_text[masked_index] = "[MASK]"
print(tokenized_text)
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
tokens_tensor = torch.tensor([indexed_tokens])
output = model(tokens_tensor)
print(output)
print()

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


['i', 'am', '[MASK]', 'student']
MaskedLMOutput(loss=None, logits=tensor([[[-7.0836, -7.1535, -7.0896,  ..., -6.3079, -6.1164, -3.7147],
         [-7.9648, -8.0580, -8.0186,  ..., -6.8658, -6.6078, -4.2644],
         [-7.0189, -7.0385, -7.1028,  ..., -6.4154, -5.8327, -3.5333],
         [-8.5992, -8.7210, -8.6977,  ..., -7.4474, -7.0835, -4.4442]]],
       grad_fn=<AddBackward0>), hidden_states=None, attentions=None)



In [5]:
import torch

In [6]:
x = torch.randn(100,100).clone().detach()
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = torch.nn.Linear(100,100,bias=True)
        self.linear2 = torch.nn.Linear(100,10,bias=True)
        self.linear3 = torch.nn.Linear(10,5,bias=True)
    
    def forward(self,x):
        x = self.linear1(x)
        x = self.linear2(x)
        x = self.linear3(x)
        return x
    
model = Model()
print([name for name in model.parameters()])


[Parameter containing:
tensor([[-0.0047, -0.0510, -0.0929,  ..., -0.0600, -0.0602,  0.0653],
        [-0.0147,  0.0543,  0.0725,  ..., -0.0117, -0.0229,  0.0279],
        [ 0.0608,  0.0683, -0.0976,  ..., -0.0792,  0.0810,  0.0440],
        ...,
        [-0.0344,  0.0899, -0.0403,  ...,  0.0380, -0.0524, -0.0115],
        [ 0.0288,  0.0027, -0.0553,  ..., -0.0563, -0.0044, -0.0741],
        [ 0.0607, -0.0251,  0.0514,  ..., -0.0682, -0.0392, -0.0653]],
       requires_grad=True), Parameter containing:
tensor([-0.0917,  0.0129,  0.0551,  0.0756,  0.0483, -0.0682, -0.0937, -0.0856,
         0.0308,  0.0997, -0.0360, -0.0502, -0.0268,  0.0170,  0.0920,  0.0172,
         0.0224, -0.0535,  0.0838, -0.0194, -0.0273, -0.0954,  0.0233, -0.0741,
        -0.0765,  0.0019,  0.0375, -0.0998,  0.0346,  0.0691, -0.0162,  0.0442,
         0.0222,  0.0361,  0.0156, -0.0923, -0.0576,  0.0794,  0.0505, -0.0670,
        -0.0765,  0.0854, -0.0078, -0.0529,  0.0047,  0.0612,  0.0594, -0.0157,
         0.00

In [7]:
import torch
print(torch.softmax(torch.Tensor(2,4),dim=0))

tensor([[0.0000, 0.5000, 0.5000, 0.5000],
        [1.0000, 0.5000, 0.5000, 0.5000]])


In [8]:
def tokenize(text, tokenizer):
    # berts tokenize ways
    # tokenize the [unused12345678910]
    D = [f"[unused{i}]" for i in range(10)]
    textraw = [text]
    for delimiter in D:
        ntextraw = []
        for i in range(len(textraw)):
            t = textraw[i].split(delimiter)
            for j in range(len(t)):
                ntextraw += [t[j]]
                if j != len(t)-1:
                    ntextraw += [delimiter]
        textraw = ntextraw
    text = []
    for t in textraw:
        if t in D:
            text += [t]
        else:
            tokens = tokenizer.tokenize(t, add_special_tokens=False)
            for tok in tokens:
                text += [tok]

    for idx, t in enumerate(text):
        if idx + 3 < len(text) and t == "[" and text[idx+1] == "[UNK]" and text[idx+2] == "]":
            text = text[:idx] + ["[MASK]"] + text[idx+3:]

    return text

In [9]:
from transformers import AutoTokenizer

token = "i just say ,you are right,and i believe you forever"
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
print(tokenize(token,tokenizer))

['i', 'just', 'say', ',', 'you', 'are', 'right', ',', 'and', 'i', 'believe', 'you', 'forever']


In [2]:
d = {1:"a",2:"b"}
print(list(d.keys()))

[1, 2]
